import argparse
import os
import subprocess
import sys
from pathlib import Path
from typing import Optional, Tuple

TASK_NAME = "HERMES-Tech-Intelligence"
# Repository root derived from this file's location so the installer is
# correct regardless of the directory it is invoked from.
PROJECT_ROOT = Path(__file__).resolve().parents[2]
LAUNCHER_SCRIPT_PATH = PROJECT_ROOT / "data" / "runtime" / "hermes_startup.bat"


def build_task_parameters() -> Tuple[str, str, str, str]:
    """Generates dynamic, absolute parameters for Windows Task Scheduler registration.

    The scheduled task launches a generated launcher script which ``cd /d``s
    into the repository root and then starts the HERMES supervisor. Task
    Scheduler cannot set a working directory for command actions, and the
    supervisor (and the API/daemon children it spawns) resolve every relative
    path (config/, data/, logs/) against their working directory — so the
    ``cd /d`` step is what makes the task correct from any logon context.
    """
    python_exe = str(Path(sys.executable).resolve())
    working_dir = str(PROJECT_ROOT)
    action_cmd = str(LAUNCHER_SCRIPT_PATH)
    return TASK_NAME, python_exe, working_dir, action_cmd


def launcher_script_body() -> str:
    """Returns the content of the generated startup launcher script."""
    python_exe = str(Path(sys.executable).resolve())
    return "\r\n".join([
        "@echo off",
        "rem Generated by app.runtime.install_windows — do not edit by hand.",
        f'cd /d "{PROJECT_ROOT}"',
        f'"{python_exe}" -m app.runtime.supervisor',
        "",
    ])


def write_launcher_script(script_path: Optional[Path] = None) -> Path:
    """Writes the launcher script that the scheduled task executes."""
    target = Path(script_path) if script_path else LAUNCHER_SCRIPT_PATH
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(launcher_script_body(), encoding="utf-8")
    return target


def register_task_script_body(task_name: str, launcher_path: str) -> str:
    """Returns a PowerShell script that registers the logon task WITHOUT elevation.

    ``schtasks /create /sc ONLOGON`` requires administrator rights, but the
    Task Scheduler COM API (``Register-ScheduledTask``) can register a
    per-user logon task that runs only when the user is logged on, with
    limited privileges — no elevation prompt required. That is exactly the
    HERMES model (local, interactive, current user), so this is the primary
    registration path.
    """
    return "\r\n".join([
        "$ErrorActionPreference = 'Stop'",
        f"$launcher = '{launcher_path}'",
        f"$taskName = '{task_name}'",
        "$user = \"$env:USERDOMAIN\\$env:USERNAME\"",
        "$action = New-ScheduledTaskAction -Execute $launcher",
        "$trigger = New-ScheduledTaskTrigger -AtLogOn -User $user",
        "$settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries "
        "-DontStopIfGoingOnBatteries -StartWhenAvailable "
        "-ExecutionTimeLimit ([TimeSpan]::Zero)",
        "$principal = New-ScheduledTaskPrincipal -UserId $user "
        "-LogonType Interactive -RunLevel Limited",
        "Register-ScheduledTask -TaskName $taskName -Action $action "
        "-Trigger $trigger -Settings $settings -Principal $principal -Force | Out-Null",
        "Write-Output 'REGISTERED'",
        "",
    ])


def register_task_via_com(task_name: str, launcher_path: str) -> Tuple[bool, str]:
    """Registers the logon task via the non-elevated Task Scheduler COM API."""
    import tempfile
    script_body = register_task_script_body(task_name, launcher_path)
    fd, script_path = tempfile.mkstemp(suffix=".ps1")
    os.close(fd)
    try:
        Path(script_path).write_text(script_body, encoding="utf-8")
        cmd = [
            "powershell",
            "-NoProfile",
            "-ExecutionPolicy", "Bypass",
            "-File", script_path,
        ]
        res = subprocess.run(cmd, capture_output=True, text=True, check=False)
        out = (res.stdout or "").strip()
        if res.returncode == 0 and "REGISTERED" in out:
            return True, "Registered via Task Scheduler COM API (no elevation)"
        err = (res.stderr or out).strip()
        return False, err or "COM registration returned no output"
    except Exception as e:
        return False, str(e)
    finally:
        try:
            Path(script_path).unlink(missing_ok=True)
        except Exception:
            pass


def query_task(task_name: str = TASK_NAME) -> Tuple[bool, str]:
    """Queries Task Scheduler to check if the task exists."""
    cmd = ["schtasks", "/query", "/tn", task_name, "/fo", "LIST"]
    try:
        res = subprocess.run(cmd, capture_output=True, text=True, check=False)
        if res.returncode == 0 and task_name.lower() in res.stdout.lower():
            return True, res.stdout
        return False, res.stderr or res.stdout
    except Exception as e:
        return False, str(e)


def install_scheduled_task(dry_run: bool = False) -> Tuple[bool, str]:
    """
    Registers HERMES autonomous runtime as a logon scheduled task for the current user.
    """
    task_name, python_exe, working_dir, action_cmd = build_task_parameters()

    if dry_run:
        print("=" * 65)
        print("HERMES — WINDOWS TASK SCHEDULER INSTALLATION (DRY RUN)")
        print("=" * 65)
        print(f"Task Name:          {task_name}")
        print(f"Python Executable:  {python_exe}")
        print(f"Working Directory:  {working_dir}")
        print(f"Launcher Script:    {action_cmd}")
        print("Launcher Content (would be written):")
        for line in launcher_script_body().splitlines():
            print(f"    {line}")
        print(f"Trigger:            At User Logon (/sc ONLOGON)")
        print(f"Settings:           Launcher cd /d's into the repo, then supervisor")
        print(f"                    manages API+daemon; restarts children on failure;")
        print(f"                    single-instance lock prevents duplicates")
        print("=" * 65)
        return True, "Dry-run complete. No changes made."

    print("=" * 65)
    print("HERMES — INSTALLING WINDOWS STARTUP TASK")
    print("=" * 65)
    print(f"Task Name:          {task_name}")
    print(f"Python Executable:  {python_exe}")
    print(f"Working Directory:  {working_dir}")

    # Generate the launcher script first so the task never points at a
    # missing file. The launcher cd /d's into the repository root before
    # starting the supervisor (Task Scheduler cannot set a working dir).
    launcher_path = write_launcher_script()
    print(f"Launcher Script:    {launcher_path}")

    # Primary path: register via the Task Scheduler COM API. This creates a
    # per-user logon task with limited privileges and requires NO elevation,
    # unlike `schtasks /create /sc ONLOGON` which needs administrator rights.
    ok, msg = register_task_via_com(task_name, str(launcher_path))
    if ok:
        print(f"Registration:       {msg}")
    else:
        print(f"[Warn] COM registration failed ({msg}); falling back to schtasks.")
        # Fallback: schtasks (requires elevation; may prompt/fail).
        cmd = [
            "schtasks",
            "/create",
            "/tn",
            task_name,
            "/tr",
            str(launcher_path),
            "/sc",
            "ONLOGON",
            "/f",
        ]
        try:
            res = subprocess.run(cmd, capture_output=True, text=True, check=False)
            if res.returncode != 0:
                err = res.stderr.strip() or res.stdout.strip()
                print(f"[Error] Failed to register scheduled task: {err}")
                return False, err
        except Exception as e:
            print(f"[Error] Exception occurred during task installation: {e}")
            return False, str(e)

    # Verify task exists
    exists, query_output = query_task(task_name)
    if not exists:
        print("[Error] Registration reported success but query verification failed.")
        return False, "Task verification failed"

    print(f"Status:             INSTALLED & VERIFIED")
    print("=" * 65)
    return True, "Task successfully registered and verified"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="HERMES Windows Task Scheduler Installer")
    parser.add_argument("--dry-run", action="store_true", help="Preview scheduled task configuration without installing")
    args = parser.parse_args()
    success, msg = install_scheduled_task(dry_run=args.dry_run)
    if not success:
        sys.exit(1)
